name: micm-docs
channels:
  - conda-forge
dependencies:
  - cmake
  - doxygen
  - gfortran
  - graphviz
  - libnetcdf-dev
  - libnetcdff-dev
  - liblapack-dev
  - liblapacke-dev
  - python=3.12
  - pip
  - pip:
      - -r docs/requirements.txt