name: micm-docs
channels:
  - conda-forge
dependencies:
  - cmake
  - doxygen
  - gfortran
  - graphviz
  - libnetcdf
  - netcdf-fortran
  - liblapack
  - liblapacke
  - python=3.12
  - pip
  - pip:
      - -r docs/requirements.txt